### PR TITLE
Feed message and fix obscure error

### LINKED ISSUE #388: Empty profile page feed needs a message

### LINKED ISSUE #396: Facebook login has error
First click does not work: ERR_CONTENT_LENGTH_MISMATCH
Second click does work

### PR DESCRIPTION
**Pull request by ritmatter**
Fixes #396
Fixes #388

### CODE REVIEW

File: js/components/Feed.jsx [hunk 1]
```diff
@@ -61,6 +61,11 @@ var Feed = React.createClass({
 
   render: function() {
     var feedHeader = this.props.userId ? <FeedHeader onClick={this.handleClick}/> : '';
+    var feedText = '';
```
Comment (ritmatter) [inline js/components/Feed.jsx]: Add a brief warning message if there are no feed transactions for a given filter

File: package.json [hunk 2]
```diff
@@ -3,7 +3,7 @@
   "version": "0.0.1",
   "description": "The first and best reputation market.",
   "author": "Stephen Malina and Matt Ritter",
-  "engines": "0.10.24",
+  "engines": "0.10.30",
```
Comment (ritmatter) [inline package.json]: Appears to fix the obscure facebook error

**Comment by krazemon** [comment]
LGTM
