### PR TITLE
Fix bugs and publicize investor categories

### LINKED ISSUE #437: Message from adding a category does not go away upon changing profile pages

### LINKED ISSUE #439: Investor Categories should be public
While your investments and reps should be hidden, your investment table should be visible to everyone

### LINKED ISSUE #443: Investment Categories Table should show percentile

### LINKED ISSUE #446: Going to the login page once logged in does not re-route to the home page

### PR DESCRIPTION
**Pull request by ritmatter**
Fixes #446 
Fixes #443 
Fixes #439
Fixes #437

### CODE REVIEW

File: js/components/CategoriesTable.jsx [hunk 1]
```diff
@@ -18,6 +18,12 @@ var CategoriesTable = React.createClass({
              message: null };
   },
 
+  componentWillReceiveProps: function(newProps) {
```
Comment (ritmatter) [inline js/components/CategoriesTable.jsx]: Fixes the issue with the "just added a category" message staying after the user navigates to a different profile page.

File: js/components/LoginPage.jsx [hunk 2]
```diff
@@ -10,9 +10,16 @@ var Signup = require('./Signup.jsx');
 var Link = Router.Link;
 
 var LoginPage = React.createClass({
-  mixins: [LoggedInRoute],
+  mixins: [ Router.Navigation ],
 
   getInitialState: function() {
+    // Redirect to the home page if logged in
+    auth.loggedIn(function(loggedIn) {
```
Comment (ritmatter) [inline js/components/LoginPage.jsx]: There is a problem with transitioning in the callback of auth. I had to fix this by moving the transition into the LoginPage component and using transitionTo. This causes the login page to flash briefly, but because the auth login is now aysnc I don't see how we can avoid it for now.

File: js/components/PortfolioItem.jsx [hunk 3]
```diff
@@ -20,14 +20,21 @@ var PortfolioItem = React.createClass({
       </div>;
     }
     var name = this.props.category.category;
+    var repsAvailable = '';
```
Comment (ritmatter) [inline js/components/PortfolioItem.jsx]: Determines whether or not to show the private fields for the portfolio table. Very similar to the categories table

File: js/components/ProfilePage.jsx [hunk 4]
```diff
@@ -77,10 +77,7 @@ var ProfilePage = React.createClass({
       categoriesTable = <CategoriesTable currentUser={this.state.currentUser} user={this.state.user} />;
       feed = <Feed parent="ProfilePage" userId={this.state.user._id} filter={"all"} isSelf={isSelf}/>;
       profileBox = <ProfileBox currentUser={this.state.currentUser} user={this.state.user} />;
-
-      if (isSelf) {
-        portfolio = <PortfolioTable user={this.state.user} currentUser={this.state.currentUser}/>;
-      }
+      portfolio = <PortfolioTable user={this.state.user} currentUser={this.state.currentUser}/>;
```
Comment (ritmatter) [inline js/components/ProfilePage.jsx]: Always show the portfolio table

**Comment by krazemon** [comment]
:+

**Comment by krazemon** [comment]
LGTM
