### PR TITLE
Add color for categories search item and fix bug

### LINKED ISSUE #500: Differentiate between users and categories in search

### PR DESCRIPTION
**Pull request by krazemon**
- Categories will now also come up as blue in the search bar
- Fixed a bug where search in the categories table wasn't working

Fixes #500 #501

### CODE REVIEW

File: js/components/SearchItem.jsx [hunk 1]
```diff
@@ -20,21 +27,23 @@ var SearchItem = React.createClass({
...
       } else {
-        imgUrl = DEFAULT_LINK;
+        imgUrl = CATEGORY_LINK;
       }
-    } else {
-      imgUrl = CATEGORY_LINK;
     }
 
     img = <img className={this.state.imgClass} src={imgUrl} onError={this.handleImgError}></img>;
+    console.log(data);
```
Comment (ritmatter) [inline js/components/SearchItem.jsx]: Caught an extra log statement!

**Comment by ritmatter** [comment]
Cool, LGTM. Colors may be subject to change by our pro
