### PR TITLE
Fix invariant violation

### LINKED ISSUE #519: Invariant Violation on InvestorList
Somehow this setState() is causing a problem:

  getInvestors: function(props) {
    var idList = [];
    var length = props.category.investors.length;
    if (length === 0) {
      return;
    }

    for (var i = 0; i < length; i++) {
      idList.push(props.category.investors[i].id);
    }
    var url = '/api/users/list/byids';
    var data = { idList: idList };
    $.ajax({
      url: url,
      data: data,
      success: function(investors) {
        this.setState({ investors: investors });
      }.bind(this),

Perhaps this could be fixed by moving the ajax calls higher?

### PR DESCRIPTION
**Pull request by ritmatter**
Fixes #519

### CODE REVIEW

File: js/components/CategoriesItem.jsx [hunk 1]
```diff
@@ -7,11 +7,50 @@ var ScoreBar = require('./ScoreBar.jsx');
 var Link = Router.Link;
 
 var CategoriesItem = React.createClass({
+  getInitialState: function() {
```
Comment (ritmatter) [inline js/components/CategoriesItem.jsx]: Moved logic to get investors up to the CategoriesItem because it was weird to have it so low

File: js/components/CategoriesItem.jsx [hunk 2]
```diff
@@ -7,11 +7,50 @@ var ScoreBar = require('./ScoreBar.jsx');
...
+    return { investors: [] };
+  },
+
+  componentDidMount: function() {
+    this.getInvestors(this.props);
+  },
+
+  // Check to see if investors need to be refreshed
+  componentWillReceiveProps: function(props) {
+    if (props.userId !== this.props.userId) {
```
Comment (ritmatter) [inline js/components/CategoriesItem.jsx]: Props are changed everytime you hover over the CategoriesItem. This caused a lot of unnecessary ajax calls, and the invariant violation (I think). Checking if the profile page has actual switched via the userId lets us avoid many many ajax calls

File: js/components/ProfileQuickView.jsx [hunk 3]
```diff
@@ -26,7 +26,7 @@ var ProfileQuickView = React.createClass({
     for (var i = 0; i < this.state.currentUser.categories.length; i++) {
       var category = this.state.currentUser.categories[i];
       categories.push(
-        <div className="list-group-item">
+        <div className="list-group-item" key={i}>
```
Comment (ritmatter) [inline js/components/ProfileQuickView.jsx]: These keys avoid a react warning

**Comment by krazemon** [comment]
LGTM
